Repository opendata-stuttgart/sensor.community, pull requests merged in 2020-12, with the labels that each got.

#131 :fire: remove gclid from shop links
  content/dnms/en/00-introduction.md
  content/dnms/es/00-introduction.md
  content/dnms/fr/00-introduction.md
  content/dnms/pl/00-introduction.md
  content/dnms/se/00-introduction.md
  content/dnms/ua/00-introduction.md
Labels: enhancement

#130 Links to madavi.de fixed
  content/airrohr/bg/03-configure.md
  content/airrohr/cz/03-configure.md
  content/airrohr/de/03-konfiguration.md
  content/airrohr/en/03-configure.md
  content/airrohr/es/03-configure.md
  content/airrohr/it/03-configure.md
  content/airrohr/nl/03-configure.md
  content/airrohr/pl/03-configure.md
  content/airrohr/se/03-configure.md
  content/airrohr/sk/03-configure.md
  content/airrohr/ua/03-configure.md
Labels: bug

#144 feature/guide-enhancements
  content/airrohr/de/01-firmware.md
  content/airrohr/de/02-aufbau.md
  content/airrohr/en/01-firmware.md
  content/airrohr/en/02-assemble.md
Labels: enhancement

#145 feature/russian-translation
  content/airrohr/ru/01-firmware.md
  content/airrohr/ru/04-register.md
  content/airrohr/ru/05-troubleshoot.md
  src/routes/endpoints/airrohr/ru/index.json.js
Labels: documentation

#133 Much text and steps added
  content/airrohr/nl/05-troubleshoot.md
Labels: enhancement

#134 Added URLs to a Dutch shop and some extra text
  content/airrohr/nl/00-introduction.md
Labels: enhancement

#135 Added explanatory text and steps.
  content/airrohr/nl/01-firmware.md
Labels: enhancement

#136 Text additions and a part about testing the station
  content/airrohr/nl/02-assemble.md
Labels: enhancement

#137 Text additions and explanations, madavi URL change
  content/airrohr/nl/03-configure.md
Labels: enhancement

#147 Update 03-configure.md
  content/airrohr/ru/03-configure.md
Labels: documentation

#148 Update 02-assemble.md
  content/airrohr/nl/02-assemble.md
  content/airrohr/ru/02-assemble.md
  static/docs/airrohr/sds_01.png
  static/docs/airrohr/sds_02.png
  static/docs/airrohr/sds_03.png
  static/docs/airrohr/sds_04.png
  static/docs/airrohr/sds_05.png
  static/index.css
Labels: documentation, enhancement
