Repository opendata-stuttgart/sensor.community, pull requests merged in 2020-05, with the labels that each got.

#57 Added build instructions in Slovak
  content/airrohr/sk/00-introduction.md
  content/airrohr/sk/01-firmware.md
  content/airrohr/sk/02-assemble.md
  content/airrohr/sk/03-configure.md
  content/airrohr/sk/04-register.md
  content/airrohr/sk/05-troubleshoot.md
Labels: documentation, enhancement

#63 added Czech translation
  locales/cz.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/utils/i18n.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#59 Initial Russian translation
  locales/ru.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/utils/i18n.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#70 bug/multilanguage-markdownguide
  src/routes/[lang]/sensors/airrohr/index.svelte
  src/routes/endpoints/airrohr/de/index.json.js
  src/routes/endpoints/airrohr/en/index.json.js
  src/routes/endpoints/airrohr/fr/index.json.js
  src/routes/endpoints/airrohr/sk/index.json.js
Labels: bug

#71 Update 02-assemble.md
  content/airrohr/fr/02-assemble.md
Labels: documentation

#72 Update 03-configure.md
  content/airrohr/fr/03-configure.md
Labels: documentation

#73 Update 05-troubleshoot.md
  content/airrohr/fr/05-troubleshoot.md
Labels: documentation

#74 Update 01-firmware.md
  content/airrohr/fr/01-firmware.md
Labels: documentation

#75 merge branchs
  README.md
  content/airrohr/de/00-einleitung.md
  content/airrohr/de/01-firmware.md
  content/airrohr/de/02-aufbau.md
  content/airrohr/de/03-konfiguration.md
  content/airrohr/de/04-registrieren.md
  content/airrohr/de/04-troubleshoot.md
  content/airrohr/fr/03-configure.md
  content/airrohr/fr/05-troubleshoot.md
  content/airrohr/sk/00-introduction.md
  content/airrohr/sk/01-firmware.md
  content/airrohr/sk/02-assemble.md
  content/airrohr/sk/03-configure.md
  content/airrohr/sk/04-register.md
  content/airrohr/sk/05-troubleshoot.md
  locales/bg.json
  locales/cz.json
  locales/it.json
  locales/ru.json
  src/components/LanguageSwitcher.svelte
  src/components/Nav.svelte
  src/routes/[lang]/_layout.svelte
  src/routes/[lang]/sensors/airrohr/index.svelte
  src/routes/endpoints/airrohr/de/index.json.js
  src/routes/endpoints/airrohr/en/index.json.js
  src/routes/endpoints/airrohr/fr/index.json.js
  src/routes/endpoints/airrohr/sk/index.json.js
  src/template.html
  src/utils/i18n.js
  src/utils/initI18n.js
Labels: bug, documentation, enhancement

#76 Update of bg.json
  locales/bg.json
Labels: documentation

#80 Upgrading dependencies
  package.json
  yarn.lock
Labels: dependencies

#81 Issue/responsive design
  site-kit/components/Docs.svelte
  site-kit/components/GuideContents.svelte
  src/components/Footer.svelte
  src/components/Nav.svelte
Labels: enhancement

#84 Initial version of nl (dutch/nederlands) translation of the web site.
  locales/nl.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/utils/initI18n.js
Labels: documentation

#85 Bulgarian content/airrohr
  bg/00-introduction.md
  bg/01-firmware.md
  bg/02-assemble.md
  bg/03-configure.md
  bg/04-register.md
  bg/05-troubleshoot.md
Labels: documentation
