Repository opendata-stuttgart/sensor.community, pull requests merged in 2020-08, with the labels that each got.

#92 NodeMCU (ESP8266) - Wording adjustments
  content/airrohr/en/01-firmware.md
Labels: documentation

#93 Update 02-assemble.md
  content/airrohr/en/02-assemble.md
Labels: documentation

#103 Remove campaigns
  src/components/Campaigns.svelte
Labels: enhancement

#104 Feature/dnms contact banner
  content/dnms/en/00-introduction.md
  content/dnms/en/03-assemble.md
  content/dnms/en/04-configure.md
  content/dnms/en/06-troubleshoot.md
  package.json
  postcss.config.js
  site-kit/base.css
  static/index.css
  yarn.lock
Labels: documentation, enhancement

#105 feature/spanish-translation
  README.md
  content/airrohr/es/00-introduction.md
  content/airrohr/es/01-firmware.md
  content/airrohr/es/02-assemble.md
  content/airrohr/es/03-configure.md
  content/airrohr/es/04-register.md
  content/airrohr/es/05-troubleshoot.md
  locales/bg.json
  locales/cz.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/nl.json
  locales/pl.json
  locales/ru.json
  locales/sk.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/routes/[lang]/sensors/index.svelte
  src/routes/endpoints/airrohr/es/index.json.js
  src/utils/i18n.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#106 feature/update-dependencies
  package.json
  yarn.lock
Labels: dependencies
