Repository opendata-stuttgart/sensor.community, pull requests merged in 2020-10, with the labels that each got.

#116 spanish dnsm translation
  content/dnms/es/00-introduction.md
  content/dnms/es/01-firmware.md
  content/dnms/es/02-PCBs.md
  content/dnms/es/03-assemble.md
  content/dnms/es/04-configure.md
  content/dnms/es/05-register.md
  content/dnms/es/06-troubleshoot.md
  locales/de.json
  locales/en.json
  src/routes/endpoints/dnms/es/index.json.js
Labels: documentation

#115 Add Italian translation for airrohr
  content/airrohr/it/00-introduction.md
  content/airrohr/it/01-firmware.md
  content/airrohr/it/02-assemble.md
  content/airrohr/it/03-configure.md
  content/airrohr/it/04-register.md
  content/airrohr/it/05-troubleshoot.md
  src/routes/endpoints/airrohr/it/index.json.js
Labels: documentation, enhancement

#120 Bug/contributors page
  src/routes/[lang]/contributors.svelte
  src/routes/[lang]/index.svelte
  static/base.css
  static/images/contributors/david-lackovic.jpg
  static/images/contributors/lukas-mocek.jpg
  static/images/contributors/pierre-jean-gueno.jpg
  static/images/contributors/rajko-zschiegner.jpg
  static/index.css
  tailwind.js
Labels: bug

#122 feature/ukraine-translation
  content/dnms/ua/00-introduction.md
  content/dnms/ua/01-firmware.md
  content/dnms/ua/02-PCBs.md
  content/dnms/ua/03-assemble.md
  content/dnms/ua/04-configure.md
  content/dnms/ua/05-register.md
  content/dnms/ua/06-troubleshoot.md
  locales/ua.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/routes/endpoints/airrohr/ua/index.json.js
  src/routes/endpoints/dnms/ua/index.json.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#123 feature/ukraine translation
  content/airrohr/ua/00-introduction.md
  content/airrohr/ua/01-firmware.md
  content/airrohr/ua/02-assemble.md
  content/airrohr/ua/03-configure.md
  content/airrohr/ua/04-register.md
  content/airrohr/ua/05-troubleshoot.md
Labels: documentation, enhancement

#124 feature/swedish-translation
  content/airrohr/se/00-introduction.md
  content/airrohr/se/01-firmware.md
  content/airrohr/se/02-assemble.md
  content/airrohr/se/03-configure.md
  content/airrohr/se/04-register.md
  content/airrohr/se/05-troubleshoot.md
  content/dnms/se/00-introduction.md
  content/dnms/se/01-firmware.md
  content/dnms/se/02-PCBs.md
  content/dnms/se/03-assemble.md
  content/dnms/se/04-configure.md
  content/dnms/se/05-register.md
  content/dnms/se/06-troubleshoot.md
  locales/se.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/routes/endpoints/airrohr/se/index.json.js
  src/routes/endpoints/dnms/se/index.json.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#125 bug/iban
  src/routes/[lang]/donate.svelte
Labels: bug
