Repository opendata-stuttgart/sensor.community, pull requests merged in 2020-04, with the labels that each got.

#35 Feature/markdown guide
  content/airrohr/de/00-einleitung.md
  content/airrohr/en/00-introduction.md
  content/airrohr/en/01-firmware.md
  content/airrohr/en/02-assemble.md
  content/airrohr/en/03-configure.md
  content/airrohr/en/04-register.md
  content/airrohr/en/05-troubleshoot.md
  package-lock.json
  package.json
  site-kit/base.css
  site-kit/components/Docs.svelte
  site-kit/components/Icon.svelte
  site-kit/components/Icons.svelte
  site-kit/components/Section.svelte
  site-kit/index.mjs
  src/routes/[lang]/index.svelte
  src/routes/[lang]/sensors/index.svelte
  src/template.html
  src/utils/generate_docs.js
  static/docs/airrohr-wiring-sds011-bme280.jpg
  static/docs/airrohr_config_initial.png
  static/docs/bme280-tied-to-tube.jpeg
  static/docs/meine_luftdaten_mysensors_de.png
  static/docs/meine_luftdaten_node_settings_additional_de.png
  static/docs/meine_luftdaten_node_settings_base_de.png
  static/docs/meine_luftdaten_node_settings_location_de.png
  static/docs/meine_luftdaten_register_sensor_de.png
  static/docs/meine_luftdaten_webpage_de.png
  static/docs/nodemcu-v3-bme280.jpeg
  static/docs/nodemcu-v3-schaltplan-sds011.jpg
  static/docs/particulate-matter-air-quality-sensor-kit.jpeg
  static/docs/position-bme280.jpeg
  static/docs/sds011-jammed-into-tube.jpeg
  static/docs/sds011-with-tube.jpeg
  static/docs/solder-a-bme-280.jpeg
  static/docs/solder-bme-280.jpeg
  static/docs/tie-air-quality-sensor- together.jpeg
  static/docs/tie-together-1.png
  static/docs/tie-together-2.png
  static/docs/tie-together-3.png
  static/docs/tie-together-4.png
  static/docs/tie-together-5.png
  static/docs/tie-together-6.png
  static/index.css
  yarn.lock
Labels: documentation

#39 update package.json
  package.json
  rollup.config.js
  src/routes/[lang]/blog/_posts.js
  yarn.lock
Labels: dependencies

#40 merge develop to master
  content/airrohr/de/00-einleitung.md
  content/airrohr/en/00-introduction.md
  content/airrohr/en/01-firmware.md
  content/airrohr/en/02-assemble.md
  content/airrohr/en/03-configure.md
  content/airrohr/en/04-register.md
  content/airrohr/en/05-troubleshoot.md
  locales/en.json
  package-lock.json
  package.json
  rollup.config.js
  site-kit/base.css
  site-kit/components/Docs.svelte
  site-kit/components/Icon.svelte
  site-kit/components/Icons.svelte
  site-kit/components/Section.svelte
  site-kit/index.mjs
  site-kit/yarn.lock
  src/components/Footer.svelte
  src/routes/[lang]/blog/[slug].svelte
  src/routes/[lang]/blog/_posts.js
  src/routes/[lang]/index.svelte
  src/routes/[lang]/sensors/index.svelte
  src/template.html
  src/utils/generate_docs.js
  static/docs/airrohr-wiring-sds011-bme280.jpg
  static/docs/airrohr_config_initial.png
  static/docs/bme280-tied-to-tube.jpeg
  static/docs/meine_luftdaten_mysensors_de.png
  static/docs/meine_luftdaten_node_settings_additional_de.png
  static/docs/meine_luftdaten_node_settings_base_de.png
  static/docs/meine_luftdaten_node_settings_location_de.png
  static/docs/meine_luftdaten_register_sensor_de.png
  static/docs/meine_luftdaten_webpage_de.png
  static/docs/nodemcu-v3-bme280.jpeg
  static/docs/nodemcu-v3-schaltplan-sds011.jpg
  static/docs/particulate-matter-air-quality-sensor-kit.jpeg
  static/docs/position-bme280.jpeg
  static/docs/sds011-jammed-into-tube.jpeg
  static/docs/sds011-with-tube.jpeg
  static/docs/solder-a-bme-280.jpeg
  static/docs/solder-a-bme-280.jpg
  static/docs/solder-bme-280.jpeg
  static/docs/tie-air-quality-sensor- together.jpeg
  static/docs/tie-together-1.png
  static/docs/tie-together-2.png
  static/docs/tie-together-3.png
  static/docs/tie-together-4.png
  static/docs/tie-together-5.png
  static/docs/tie-together-6.png
  static/index.css
  yarn.lock
Labels: dependencies, enhancement

#42 :bug: fixed path to github edit url
  site-kit/components/Docs.svelte
Labels: bug

#43 Github edit links
  site-kit/components/Docs.svelte
Labels: bug

#44 Improve the language of configuration and registration sections.
  content/airrohr/en/03-configure.md
  content/airrohr/en/04-register.md
Labels: documentation

#45 Feature/french translation
  .gitignore
  content/airrohr/fr/00-introduction.md
  content/airrohr/fr/01-firmware.md
  content/airrohr/fr/02-assemblage.md
  content/airrohr/fr/02-assemble.md
  content/airrohr/fr/03-configuration.md
  content/airrohr/fr/03-configure.md
  content/airrohr/fr/04-register.md
  content/airrohr/fr/05-troubleshoot.md
Labels: documentation

#38 Added Slovak translation
  locales/sk.json
  src/components/LanguageSwitcher.svelte
  src/components/Nav.svelte
  src/routes/[lang]/_layout.svelte
  src/utils/initI18n.js
Labels: documentation

#49 slovak translation
  locales/sk.json
  src/components/LanguageSwitcher.svelte
  src/routes/[lang]/_layout.svelte
  src/utils/i18n.js
  src/utils/initI18n.js
Labels: documentation, enhancement

#51 bug/documentation
  README.md
Labels: bug
