Repository opendata-stuttgart/sensor.community, pull requests merged in 2021-02, with the labels that each got.

#155 feature/dep-updates
  package.json
  yarn.lock
Labels: dependencies

#159 Update 02-assemble.md
  content/airrohr/fr/02-assemble.md
Labels: documentation

#164 no2-campaign
  src/routes/[lang]/campaign/no2/index.svelte
  static/index.css
Labels: enhancement

#165 bug/fr-translation
  content/airrohr/fr/02-assemble.md
Labels: bug

#163 Update pl.json
  locales/pl.json
Labels: documentation, enhancement

#166 bug/line-wrap-fix-translations
  content/airrohr/bg/02-assemble.md
  content/airrohr/cz/02-assemble.md
  content/airrohr/de/02-aufbau.md
  content/airrohr/en/02-assemble.md
  content/airrohr/nl/02-assemble.md
  content/airrohr/pl/02-assemble.md
  content/airrohr/ru/02-assemble.md
  content/airrohr/se/02-assemble.md
  content/airrohr/sk/02-assemble.md
  content/airrohr/ua/02-assemble.md
Labels: bug

#162 Czech DNMS Translation
  content/dnms/cz/00-introduction.md
  content/dnms/cz/01-firmware.md
  content/dnms/cz/02-PCBs.md
  content/dnms/cz/03-assemble.md
  content/dnms/cz/04-configure.md
  content/dnms/cz/05-register.md
  content/dnms/cz/06-troubleshoot.md
Labels: documentation
